name: 'test_project'
version: '1.0.0'
config-version: 2

# Points to target in profiles.yml
profile: 'test_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - "CREATE SCHEMA IF NOT EXISTS f1_staging;"
  - "CREATE SCHEMA IF NOT EXISTS f1_marts;"
  - "ATTACH IF NOT EXISTS '/app/databases/formula1.duckdb' AS formula1 (READ_ONLY true);"
  - "INSTALL httpfs; LOAD httpfs; INSTALL delta; LOAD delta; CREATE OR REPLACE SECRET s3_dbt_secret (TYPE S3, KEY_ID 'GK2713753aca1d72db5325f212', SECRET 'afd53ab8d8e6f762973bab0b5a33998265530dee63cae200e1a8e065be2a4b6e', ENDPOINT 'garage:3900', REGION 'us-east-1', USE_SSL false, URL_STYLE 'path');"

models:
  test_project:
    staging:
      formula1:
        +schema: f1_staging
        +materialized: view
    marts:
      formula1:
        +schema: f1_marts
        +materialized: table
