name: 'test_project'
version: '1.0.0'
config-version: 2

# Points to target in profiles.yml
profile: 'test_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  test_project:
    materialized: table
